/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as RailRouteImport } from './routes/_rail'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as RailGraphRouteImport } from './routes/_rail/graph'
import { Route as AppLabelsLabelIdRouteImport } from './routes/_app/labels.$labelId'
import { Route as RailBoardsIndexRouteImport } from './routes/_rail/boards/index'
import { Route as RailBoardsBoardIdRouteImport } from './routes/_rail/boards/$boardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const RailRoute = RailRouteImport.update({
  id: '/_rail',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const RailGraphRoute = RailGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => RailRoute,
} as any)
const AppLabelsLabelIdRoute = AppLabelsLabelIdRouteImport.update({
  id: '/labels/$labelId',
  path: '/labels/$labelId',
  getParentRoute: () => AppRoute,
} as any)
const RailBoardsIndexRoute = RailBoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => RailRoute,
} as any)
const RailBoardsBoardIdRoute = RailBoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => RailRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof AppInboxRoute
  '/library': typeof AppLibraryRoute
  '/graph': typeof RailGraphRoute
  '/labels/$labelId': typeof AppLabelsLabelIdRoute
  '/boards/$boardId': typeof RailBoardsBoardIdRoute
  '/boards/': typeof RailBoardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof AppInboxRoute
  '/library': typeof AppLibraryRoute
  '/graph': typeof RailGraphRoute
  '/labels/$labelId': typeof AppLabelsLabelIdRoute
  '/boards/$boardId': typeof RailBoardsBoardIdRoute
  '/boards': typeof RailBoardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_rail': typeof RailRouteWithChildren
  '/_app/inbox': typeof AppInboxRoute
  '/_app/library': typeof AppLibraryRoute
  '/_rail/graph': typeof RailGraphRoute
  '/_app/labels/$labelId': typeof AppLabelsLabelIdRoute
  '/_rail/boards/$boardId': typeof RailBoardsBoardIdRoute
  '/_rail/boards/': typeof RailBoardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/library'
    | '/graph'
    | '/labels/$labelId'
    | '/boards/$boardId'
    | '/boards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/library'
    | '/graph'
    | '/labels/$labelId'
    | '/boards/$boardId'
    | '/boards'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_rail'
    | '/_app/inbox'
    | '/_app/library'
    | '/_rail/graph'
    | '/_app/labels/$labelId'
    | '/_rail/boards/$boardId'
    | '/_rail/boards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RailRoute: typeof RailRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rail': {
      id: '/_rail'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_rail/graph': {
      id: '/_rail/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof RailGraphRouteImport
      parentRoute: typeof RailRoute
    }
    '/_app/labels/$labelId': {
      id: '/_app/labels/$labelId'
      path: '/labels/$labelId'
      fullPath: '/labels/$labelId'
      preLoaderRoute: typeof AppLabelsLabelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_rail/boards/': {
      id: '/_rail/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof RailBoardsIndexRouteImport
      parentRoute: typeof RailRoute
    }
    '/_rail/boards/$boardId': {
      id: '/_rail/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof RailBoardsBoardIdRouteImport
      parentRoute: typeof RailRoute
    }
  }
}

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppLabelsLabelIdRoute: typeof AppLabelsLabelIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppLabelsLabelIdRoute: AppLabelsLabelIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface RailRouteChildren {
  RailGraphRoute: typeof RailGraphRoute
  RailBoardsBoardIdRoute: typeof RailBoardsBoardIdRoute
  RailBoardsIndexRoute: typeof RailBoardsIndexRoute
}

const RailRouteChildren: RailRouteChildren = {
  RailGraphRoute: RailGraphRoute,
  RailBoardsBoardIdRoute: RailBoardsBoardIdRoute,
  RailBoardsIndexRoute: RailBoardsIndexRoute,
}

const RailRouteWithChildren = RailRoute._addFileChildren(RailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RailRoute: RailRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
